# Generated by Django 4.2.5 on 2023-10-12 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='dt_measurement',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
